# Generated by Django 5.0.2 on 2024-02-16 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('genre', models.CharField(max_length=200)),
                ('rating', models.IntegerField()),
                ('favorite', models.BooleanField()),
                ('comment', models.CharField(max_length=1000)),
            ],
        ),
    ]
