# Generated by Django 5.0.2 on 2024-02-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('genres', models.CharField(max_length=200)),
                ('num_of_eps', models.IntegerField()),
                ('img', models.CharField(max_length=200)),
            ],
        ),
    ]
