# Generated by Django 5.0.2 on 2024-02-18 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0004_remove_anime_genre_remove_anime_name_anime_anime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='comment',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='anime',
            name='current_episode',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='anime',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='anime',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='anime',
            name='status',
            field=models.CharField(choices=[('Watching', 'Watching'), ('Finished', 'Finished'), ('Plan to Watch', 'Plan to Watch')], default='Watching', max_length=50),
        ),
    ]
