# Generated by Django 5.0.2 on 2024-02-18 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0006_publicanimelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animes',
            name='genres',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='animes',
            name='img',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='animes',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='animes',
            name='num_of_eps',
            field=models.IntegerField(null=True),
        ),
    ]
